# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Pastel
#9A348E
#DA627D
#FCA17D
#86BBD8
#06969A
#33658A

# Custom
#2E154F
#2B3D67
#562C93
#5833B0
#6B50C8


add_newline = false

format = """
[î‚¶](#2E154F)\
$time\
[î‚°](fg:#2E154F bg:#2B3D67)\
$os\
$package\
[î‚°](fg:#2B3D67 bg:#562C93)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:#562C93 bg:#5833B0)\
$directory\
[î‚°](fg:#5833B0 bg:#6B50C8)\
$git_branch\
$git_status\
[î‚° ](fg:#6B50C8)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[package]
style = "bg:#2B3D67"
format = '[$symbol$version ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#2E154F"
disabled = true # Disabled by default

[directory]
style = "bg:#5833B0"
format = "[ $path ]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Contacts" = "ïŠ¹"
"Kontakter" = "ïŠ¹"
"Downloads" = "ï€™"
"Nedlastinger" = "ï€™"
"Desktop" = "ï„ˆ"
"Skrivebord" = "ï„ˆ"
"Music" = "ï€"
"Musikk" = "ï€"
"Movies" = "ï€ˆ"
"Filmer" = "ï€ˆ"
"Pictures" = "ï€¾"
"Bilder" = "ï€¾"
"OneDrive" = "ïƒ‚ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

# VCS Branch
[git_branch]
symbol = "ï˜"
style = "bg:#6B50C8"
format = '[ $symbol $branch]($style)'

[git_status]
disabled = false
style = "bg:#6B50C8"
format = '[ $all_status$ahead_behind]($style)'

# Languages
[c]
symbol = "î˜ "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#5B5DAA"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#562C93"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2E154F"
format = '[$time ]($style)'
